apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: nginx-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: nginx-vpa-demo
  updatePolicy:
    updateMode: "Auto"

##for vpa resource restriction 

# apiVersion: autoscaling.k8s.io/v1
# kind: VerticalPodAutoscaler
# metadata:
#   name: nginx-vpa
# spec:
#   targetRef:
#     apiVersion: "apps/v1"
#     kind: Deployment
#     name: nginx-vpa-demo
#   updatePolicy:
#     updateMode: "Auto"
#   resourcePolicy:
#     containerPolicies:
#     - containerName: nginx
#       maxAllowed:
#         cpu: 1000m      # VPA won't go above this
#         memory: 512Mi
#       minAllowed:
#         cpu: 10m        # VPA won't go below this
#         memory: 10Mi